### ISSUE TITLE
Can't rewind track when transcoding enabled

### ISSUE THREAD

**Issue by shams00** [BlitterStudio/MB_SubSonic#54]
**Describe the bug**
Can't rewind track when transcoding enabled.  Without transcoding it works fine.

**To Reproduce**
1. Enable transcoding in MB_SubSonic plugin configuration (192 Kbps)
2. Start playing track from airsonic server
3. Try to rewind track by dragging the thumb
4. Track is not rewinded, thumb returns to position it was before dragging.

**Expected behavior**
Track is rewinded.

**Additional context**
Original  file is of flac format, transcoding set to 192 Kbps.

Media server: arisonic 10.5.0-RELEASE
OS: Windows 10 Pro 1909
Music Bee: 3.3.7310 P
Sub Sonic client plugin: 2.28.0

**Comment by midwan** [comment]
I cannot recreate this issue with the latest versions of MusicBee, the pluign and AirSonic server.
It's been quite a while since this was reported of course, so it may have been a bug somewhere that got fixed since. :)

I'm closing this issue, but if you still have problems with transcoding please let me know, and we can check again.
